# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_cuda102:
    runs-on: ubuntu-18.04
    container:
      image: openxrlab/xrmocap_runtime:ubuntu1804_x64_cu102_py38_torch181_mmcv153
      credentials:
        username: ${{secrets.DOCKERHUB_USERNAME}}
        password: ${{secrets.DOCKERHUB_PWD}}
      volumes:
        - /workflow/mmhuman3d_container:/home/runner/work/mmhuman3d/mmhuman3d
    steps:
      - name: Show path
        run: |
          pwd
      - name: Show ls
        run: |
          ls
      - uses: actions/checkout@v2
      - name: Show ls again
        run: |
          ls
      - name: Show conda env
        run: |
          source /root/.bashrc
          conda info -e
          conda activate openxrlab
      - name: Prepare test data
        run: |
          sh scripts/download_test_data.sh
      - name: Build and install
        run: |
          rm -rf xrmocap.egg-info
          pip install -e .
      - name: Run unittests and generate coverage report
        run: |
          coverage run --source xrmocap -m pytest tests/
          coverage xml
          coverage report -m
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage.xml
          flags: unittests
          env_vars: OS,PYTHON
          name: codecov-umbrella
          fail_ci_if_error: false
